### ISSUE TITLE
wifi manager not open site.

### ISSUE THREAD

**Issue by martcs** [roberttidey/RotaryEncoderButton#1]
after upload ino RptaryEncoderButton, esp showing ssid,can connect with password used in baseconfig. but when try go to 192.168.4.1 nothing is shown. I use wifimanager library from your github. I try your irblaster project, there all working fine, address 192.168.4.1 showing wifimanager page an can select wifi access point, after that of course esp connect and get ip.  I use nodemcu temporary without wiring encoder.

**Comment by roberttidey** [comment]
Is 192.168.4.1 timing out or just showing nothing? I want to see if your esp is timing out and going into deep sleep or it is in an active state.

With the hardware and encoder connections as suggested one can disable the deep sleep operation by pushing down the encoder switch while turning on by rotating it. That disables the deep sleep. 

One can also change the default timeout in the code by changing noChangeTimeout at the top of the code before compiling and uploading it.

**Comment by roberttidey** [comment]
Sorry, a rogue version had been uploaded causing wifimanager to fail to support network configuration.

I have corrected this now.

**Comment by martcs** [comment]
Yes, now working :)
